@host = http://localhost:5001

###
GET {{host}}/

###
GET {{host}}/api/characters

###
POST {{host}}/api/characters
Content-Type: application/json

{
  "name": "Muminek",
  "description": "Mieszkaniec Doliny Muminków",
  "species": "Muminek",
  "isHibernating": false
}

###
GET {{host}}/api/artifacts

###
POST {{host}}/api/artifacts
Content-Type: application/json

{
  "name": "Kapelusz Tajemniczego Pana",
  "description": "Zamienia rzeczy w chmury"
}